### PR TITLE
Request for feedback: First setup to limiting final ngram size

### PR DESCRIPTION
**Pull request by psmit**
Not a real PR this, just a request for feedback regarding my setup (naming things is hard and I've definitely not done my best job on that yet).

Do you have any concerns if this would work correctly? Of course I would have to fine tune the constants (or make them configurable). 

At this moment I'm not doing m_kn->find_coeffs every time I increase the pruning scale, I'm still reasoning if that would be a good thing to do or not.

### CODE REVIEW

**Comment by psmit** [comment]
The algorithm is working very well, but the messages it prints are still a bit ugly... I'll clean them up tomorrow and then it can be merged if you want.

**Comment by psmit** [comment]
I made some (mainly cosmetic) changes and I'll test them today.

**Comment by vsiivola** [comment]
Great, sounds good! I'll wait for the last changes before merging.

**Comment by psmit** [comment]
Can be merged I think. If I come across any bugs later I'll send a fix

**Comment by vsiivola** [comment]
Merged. Thanks!

**Pull request merged**
